#include<stdio.h>
#include<math.h>
#include<cmath>
#include<stdlib.h>
#include<string.h>
#include<time.h>
#include<iostream>
#include<fstream>
#include<iomanip>
#include<bibli_fonctions.h>
#include<TROOT.h>
#include<TRint.h>
#include<TH1F.h>
#include<TH1.h>
#include<TH2F.h>
#include<TCanvas.h>
#include<TF1.h>
#include<TFormula.h>
#include<TGraph.h>
#include<TGraphErrors.h>
#include<TRandom.h>
#include<Riostream.h>
